# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e01cbf6944e419dffc13b6901edab30c7e8cb119716304778267d50bd118b4bb6764ae0e69c4866a0f2018da1534ef7b0b422c1802f5d3cc60700f0f5efcd732

test:
  secret_key_base: 761afa6968beaf7334e77a125f9782a68d2bfeba645642930cbb1e2eb80632aa92c700848e97f74481edad57e401088093699322490e2b46da72e8efa5620cf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
